# Generated by Django 5.2.4 on 2025-07-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_alter_notice_options_alter_slot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
