name: R슬롯 Codespaces

on:
  create:
    types: [codespace]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
      
      - name: Create superuser
        run: |
          echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin123') if not User.objects.filter(username='admin').exists() else None" | python manage.py shell
      
      - name: Start server
        run: |
          python manage.py runserver 0.0.0.0:8000 